# Generated by Django 5.1 on 2024-08-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='ano_conclusao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='instituicao',
        ),
    ]
